trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'Build'
  displayName: 'Build job'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Use the desired Python version

  - script: |
      # Display information about the Python environment
      python --version
      pip freeze
    displayName: 'Show Python environment'

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: 'python-artifact'
    displayName: 'Publish pipeline artifact'
