name: Move to Acc Branch

on:
  pull_request:
    types:
      - closed

jobs:
  move_to_acc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Move changes to acc branch
      if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
      run: |
        git checkout acc
        git merge --no-ff --no-commit test
        # Resolve any merge conflicts if needed
        git commit -m "Merge changes from test to acc branch"
        git push origin acc
