name: Release Pipeline

on:
  pull_request:
    branches:
      - main
      - 'acc'
      - 'test'


jobs:
  trigger_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger release pipeline on PR approval
      if: github.event.review.state == 'approved'
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        az extension add --name azure-devops
        az pipelines run --name "git PR pipeline" --org "https://dev.azure.com/tejagondhi" --project 
        "Az2Git" --branch $(echo $GITHUB_REF | awk -F/ '{print $NF}')
